format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$time\n\
$character\
"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'

[directory]
format = "[$path]($style) "
style = "foam"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
Documents = "ó°ˆ™"
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "

[fill]
style = "fg:overlay"
symbol = " "

[character]
disabled = false
success_symbol = "[â¯](foam)"
error_symbol = "[â¯](love)"
vicmd_symbol = "[â®](foam)"

[git_branch]
format = "[$symbol $branch]($style) "
style = "pine"
symbol = "ï˜"

[git_commit]
tag_symbol = ' ï’ '

[git_status]
disabled = false
style = "love"
format = '([$all_status$ahead_behind]($style)) '
up_to_date = '[ âœ“ ](iris)'
untracked = '[?\($count\)](gold)'
stashed = '[\$](iris)'
modified = '[!\($count\)](gold)'
renamed = '[Â»\($count\)](iris)'
deleted = '[âœ˜\($count\)](style)'
staged = '[++\($count\)](gold)'
ahead = '[â‡¡\(${count}\)](foam)'
diverged = 'â‡•[\[](iris)[â‡¡\(${ahead_count}\)](foam)[â‡£\(${behind_count}\)](rose)[\]](iris)'
behind = '[â‡£\(${count}\)](rose)'

[time]
disabled = false
format = "[$time]($style)"
style = "rose"
time_format = "%H:%M"

[username]
disabled = true
format = "[$user]($style) "
show_always = true
style_root = "iris"
style_user = "iris"

[os]
disabled = false
format = "[$symbol]($style)"
style = "iris"

# OS Symbols
[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

# Languages
[aws]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "îŒ½  "

[buf]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "ï’ "

[c]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜ "

[conda]
style = "pine"
format = "[$symbol$environment]($style) "
disabled = false
symbol = 'ğŸ…’ '

[crystal]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜¯ "

[dart]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜ "

[docker_context]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "ïŒˆ "

[elixir]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î‰µ "

[elm]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜¬ "

[golang]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜§ "

[gradle]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î™  "

[haskell]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î· "

[haxe]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î™¦ "

[java]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î‰– "

[julia]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜¤ "

[kotlin]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜´ "

[lua]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜  "

[meson]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "ó°”· "

[nodejs]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "îœ˜ "

[nim]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "ó°†¥ "

[nix_shell]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "ïŒ“ "

[ocaml]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î™º "

[perl]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î™¾ "

[rlang]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "ó°Ÿ” "

[ruby]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î‘ "

[rust]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î¨"

[scala]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "îœ· "

[swift]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î• "

[php]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "î˜ˆ "

[python]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = 'îœ¼ '

[zig]
style = "pine"
format = "[$symbol$version]($style) "
disabled = false
symbol = "îš© "
